// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalSystem.Models;

#nullable disable

namespace RentalSystem.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    [Migration("20251204013249_Lab4_CRUD")]
    partial class Lab4_CRUD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalSystem.Models.RentOrder", b =>
                {
                    b.Property<int>("RentOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentOrderID"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TransportID")
                        .HasColumnType("bigint");

                    b.HasKey("RentOrderID");

                    b.HasIndex("TransportID");

                    b.ToTable("RentOrders");
                });

            modelBuilder.Entity("RentalSystem.Models.Transport", b =>
                {
                    b.Property<long>("TransportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransportID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("TransportID");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("RentalSystem.Models.RentOrder", b =>
                {
                    b.HasOne("RentalSystem.Models.Transport", "Transport")
                        .WithMany("RentOrders")
                        .HasForeignKey("TransportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("RentalSystem.Models.Transport", b =>
                {
                    b.Navigation("RentOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
